package by.example.ClientServer.controller.request;

public enum RequestMode {
    ADD_STUDENT,
    DELETE_STUDENT_BY_SURNAME_OR_GROUP_NUMBER,
    DELETE_STUDENT_BY_SURNAME,
    DELETE_STUDENT_BY_GROUP_NUMBER,
    SEARCH_STUDENT_BY_SURNAME_OR_GROUP_NUMBER,
    SEARCH_STUDENT_BY_SURNAME,
    SEARCH_STUDENT_BY_GROUP_NUMBER,
    NEXT_PAGE,
    PREV_PAGE,
    FIRST_PAGE,
    LAST_PAGE,
    GROUP_NUMBER_LIST,
    UPDATE_TABLE,
    TABLE_PARAMETERS,
    SAVE_FILE,
    OPEN_FILE,
    FILE_NAME_LIST,
    FIRST_SEARCH_PAGE,
    LAST_SEARCH_PAGE,
    NEXT_SEARCH_PAGE,
    PREV_SEARCH_PAGE,
    CLEAR_LIST
}
